services:
  db:
    container_name: ah-gch-auth-db
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - net

  app:
    container_name: ah-gch-auth
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      args:
        - USER=$USER
    volumes:
      - $HOME/Share:/home/$USER/Share
    ports:
      - 4444:4444
    depends_on:
      - db
    restart: no
    networks:
      - net

networks:
  net:
