services:
  db:
    container_name: ah-gch-auth-db
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${PGPORT}
      POSTGRES_DB: ${POSTGRES_DB}
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    ports:
      - ${PGPORT}:${PGPORT}
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 53s
      timeout: 5s
      retries: 10
 
  app:
    container_name: ah-gch-auth
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      args:
        - USER=$USER
    volumes:
      - $HOME/Share:/home/$USER/Share
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - db
    restart: no
    networks:
      - net

networks:
  net:

volumes:
  pgdata:
